[2024-10-29T13:18:18.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T13:18:18.358+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl_with_excel.transform_task manual__2024-10-29T13:17:29.341193+00:00 [queued]>
[2024-10-29T13:18:18.378+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl_with_excel.transform_task manual__2024-10-29T13:17:29.341193+00:00 [queued]>
[2024-10-29T13:18:18.386+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T13:18:18.436+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_task> on 2024-10-29 13:17:29.341193+00:00
[2024-10-29T13:18:18.511+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl_with_excel', 'transform_task', 'manual__2024-10-29T13:17:29.341193+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_pg.py', '--cfg-path', '/tmp/tmpe095f4xv']
[2024-10-29T13:18:18.502+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T13:18:18.527+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2024-10-29T13:18:18.528+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask transform_task
[2024-10-29T13:18:18.766+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_to_postgres_etl_with_excel.transform_task manual__2024-10-29T13:17:29.341193+00:00 [running]> on host d1cc6afd9541
[2024-10-29T13:18:19.208+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl_with_excel' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T13:17:29.341193+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T13:17:29.341193+00:00'
[2024-10-29T13:18:19.226+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T13:18:20.774+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T13:18:20.800+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T13:18:20.801+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl_with_excel, task_id=transform_task, run_id=manual__2024-10-29T13:17:29.341193+00:00, execution_date=20241029T131729, start_date=20241029T131818, end_date=20241029T131820
[2024-10-29T13:18:21.002+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T13:18:21.762+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T13:18:21.795+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
