[2024-10-29T09:35:17.246+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T09:35:17.362+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl_with_excel.transform_task manual__2024-10-29T09:33:07.122063+00:00 [queued]>
[2024-10-29T09:35:17.417+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl_with_excel.transform_task manual__2024-10-29T09:33:07.122063+00:00 [queued]>
[2024-10-29T09:35:17.419+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T09:35:17.482+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_task> on 2024-10-29 09:33:07.122063+00:00
[2024-10-29T09:35:17.508+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T09:35:17.512+0000] {standard_task_runner.py:72} INFO - Started process 163 to run task
[2024-10-29T09:35:17.510+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl_with_excel', 'transform_task', 'manual__2024-10-29T09:33:07.122063+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/pg_my.py', '--cfg-path', '/tmp/tmptrv7xal7']
[2024-10-29T09:35:17.516+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask transform_task
[2024-10-29T09:35:17.704+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_to_postgres_etl_with_excel.transform_task manual__2024-10-29T09:33:07.122063+00:00 [running]> on host fe15dc428079
[2024-10-29T09:35:17.983+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl_with_excel' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T09:33:07.122063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T09:33:07.122063+00:00'
[2024-10-29T09:35:17.986+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T09:35:18.623+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T09:35:18.659+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T09:35:18.660+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl_with_excel, task_id=transform_task, run_id=manual__2024-10-29T09:33:07.122063+00:00, execution_date=20241029T093307, start_date=20241029T093517, end_date=20241029T093518
[2024-10-29T09:35:18.811+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T09:35:18.869+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T09:35:18.877+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
