[2024-10-30T00:49:34.332+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T00:49:34.679+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_redshift_etl.extract_task scheduled__2024-10-29T00:00:00+00:00 [queued]>
[2024-10-30T00:49:34.707+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_redshift_etl.extract_task scheduled__2024-10-29T00:00:00+00:00 [queued]>
[2024-10-30T00:49:35.436+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-30T00:49:35.633+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-29 00:00:00+00:00
[2024-10-30T00:49:35.645+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_redshift_etl', 'extract_task', 'scheduled__2024-10-29T00:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/reds.py', '--cfg-path', '/tmp/tmp5wjw20en']
[2024-10-30T00:49:35.656+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask extract_task
[2024-10-30T00:49:35.658+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T00:49:35.693+0000] {standard_task_runner.py:72} INFO - Started process 65 to run task
[2024-10-30T00:49:36.049+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_redshift_etl.extract_task scheduled__2024-10-29T00:00:00+00:00 [running]> on host 7bbdde9419fb
[2024-10-30T00:49:36.904+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_redshift_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-29T00:00:00+00:00'
[2024-10-30T00:49:36.910+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T00:49:37.340+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-30T00:49:41.097+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T00:49:41.289+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T00:49:41.294+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_redshift_etl, task_id=extract_task, run_id=scheduled__2024-10-29T00:00:00+00:00, execution_date=20241029T000000, start_date=20241030T004934, end_date=20241030T004941
[2024-10-30T00:49:41.624+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T00:49:41.736+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-30T00:49:41.801+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
